### ISSUE TITLE
Clipboard copy support code adds extra (unwanted) code element

### ISSUE THREAD

**Issue by tedyoung** [reeseschultz/11r#11]
Code blocks end up doubly nested due to error in copy.js (throws off CSS and triggers application of `:not(pre) > code` in my base.css).

**Bug reproduction:**

Inspect the source of a code block (after the JS runs) at https://reeseschultz.github.io/11r/post/deadbeef-decrementation/.

```
<div class="content post">
    <pre class="language-nasm">
        <div class="copy">copy</div>
        <code class="language-nasm">
            <code class="language-nasm">   <-- extra!
                <span class="token comment">
... etc. ...
```

The copy.js code does this (lines 12-14):

```
      preTags[
        i
      ].innerHTML = `<div class="copy">copy</div><code class="${preTags[i].className}">${preTags[i].innerHTML}</code>`;
```

instead of (I believe) this (just insert the copy div):

```
      preTags[
        i
      ].innerHTML = `<div class="copy">copy</div>${preTags[i].innerHTML}`;
```

If there was a reason to create the extra nested `<code>` block, I couldn't figure it out (the original Codepen had it, but I'm not sure it's necessary here.)

**Comment by reeseschultz** [comment]
Hi @tedyoung!

Many thanks for investigating this problem.

I verified that the `code` block is redundant; it causes some hairy output. Your suggestion works well. I'll update the template and close this issue soon.

Please don't hesitate to submit more issues if you come across anything.

**Comment by reeseschultz** [comment]
By the way, I also refactored the [code copying script](https://github.com/reeseschultz/11r/blob/master/src/scripts/copy.js) for readability and correctness.
