### ISSUE TITLE
[BUG] Indentation not working in the code block

### ISSUE THREAD

**Issue by Nikit-Singh** [reeseschultz/11r#2]
I was checking out the template and found that indentation is not working for the code blocks. After removing the Prism.js's CSS file it works fine but elsewise there is an issue.

**Comment by Nikit-Singh** [comment]
Found out that prism.js was adding `white-space: normal;` somewhere and then I overridden it with  `white-space: pre;`.

**Comment by reeseschultz** [comment]
Thanks @Nikit-Singh, it's fixed!
