### ISSUE TITLE
[BUG] Leaving out updatedDate breaks posts

### ISSUE THREAD

**Issue by mjclemente** [reeseschultz/11r#7]
First, thank you for this project - it's fantastic. Fun to use and the output is beautiful.

**Bug description:**

Two issues here, regarding the `updatedDate` property on posts. If it's not included, I'm seeing the following error:

```
`TemplateWriterWriteError` was thrown
> (./src/includes/layouts/post.njk) [Line 3, Column 3]
  TypeError: Cannot read property 'toString' of undefined

`Template render error` was thrown:
    Template render error: (./src/includes/layouts/post.njk) [Line 3, Column 3]
      TypeError: Cannot read property 'toString' of undefined
```

It appears to be related to [this line](https://github.com/reeseschultz/11r/blob/2441b8dd587aaa60e738eb693f442cfe3f573b04/src/includes/layouts/post.njk#L27): `{% if updatedDate | string in date | string %}`, in which the ` | string in date | string ` doesn't appear to be needed (but I could be mistaken).

Removing that filter then results in the second issue - the post template outputting: `Last updated on Invalid Date.`

This appears to be because the logic on the Nunjucks if statement is backwards, checking for `updatedDate` but then only displaying the created date, and then the template tries to use `updatedDate` when it's not defined.

**Bug reproduction:**

1. Remove the `updatedDate` from a post in the project
2. `npx @11ty/eleventy`

**Expected behavior:**

The project to build without a problem.

**Describe alternatives or workarounds you've considered:**

Reversing the Nunjucks logic and removing the filter resolves the issue:

```
{% if updatedDate %}
<p class="text-sm italic">Last updated on
        <span datetime="{{ date }}">{{ updatedDate | dateDisplay }}</span>. Created on
        <span datetime="{{ date }}">{{ date | dateDisplay }}</span>.</p>
{% else %}
    <p class="text-sm italic">Created on
        <span datetime="{{ date }}">{{ date | dateDisplay }}</span>.</p>
{% endif %}
```

Happy to put in a PR to fix this if you like.

**Comment by reeseschultz** [comment]
@mjclemente thanks for the detailed bug report. Sounds like your resolution should work fine. Yep, if you don't mind, please submit a PR, mainly so you'll get credit as a contributor to this project. I appreciate your help.

**Comment by mjclemente** [comment]
Awesome. Thanks, appreciate that! 😄 

PR submitted #8
