### ISSUE TITLE
[BUG] Dates off-by-one

### ISSUE THREAD

**Issue by mjclemente** [reeseschultz/11r#9]
**Bug description:**

Post dates displayed are off by one day. That is, the date `2016-10-09` is displayed as _October 8, 2016_.

I believe this has to due with how JavaScript handles dates - I was live-coding when I encountered this and one of the people watching documented the issue here: https://www.bockensm.com/2021/03/13/javascript-dates-off-by-one/. Quoting from his post:

> JavaScript is storing the date internally as midnight UTC but converting it to the browser's local time when rendering. In other words, if my UTC offset is -5, then 00:00 on March 12, 2021 in UTC is actually 17:00 on March 11, 2021 in my time zone.

**Bug reproduction:**

1. This happens when I simply run `npm run dev`. 

**Expected behavior:**

The date displayed should match the date in the post markdown.

**Describe alternatives or workarounds you've considered:**

I think we can fix this by added the `timeZone` option to `date-display.js`, like this:

```javascript
module.exports = (date) =>
  new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'UTC',
});
```

**Additional context:**

Here's a screenshot of the markdown file and how the post is generated:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/5348419/111041087-80c40e00-8404-11eb-8896-077095dd7631.png">

<img width="719" alt="image" src="https://user-images.githubusercontent.com/5348419/111041116-aea95280-8404-11eb-8b0b-3a69a0f43b0a.png">

**Comment by reeseschultz** [comment]
You're right. Thanks for bringing this up! I'll add the `timeZone` option in a moment.

**Comment by mjclemente** [comment]
Awesome! Thanks! 🎉
